[package]
name = "lnai"
version.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "lnai"
path = "src/main.rs"

[[bin]]
name = "lore_gen"
path = "src/lore_gen_main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
lnai-training = { path = "../lnai-training", features = ["pinn"] }