use dioxus::prelude::*;
use crate::assets::{FONT_SERIF, FONT_SANS};
use crate::components::Header;

const PAGE_TITLE: &str = "THE VISION";

const MAIN_DESCRIPTION: &str =
    "Welcome to an infinite universe generated by AI completely on the fly. \
     Hit 'Start Journey', watch the moon sail past, and dive straight into cosmic customization. \
     Quick heads-up: we are totally broke right now, so the neural network runs locally \
     right on your machine — but hey, 100% data privacy and absolute zero ping!";

const CARD_1_ICON: &str = "✦";
const CARD_1_TITLE: &str = "INFINITE COSMOS";
const CARD_1_DESC: &str =
    "Interactive editor and visualization on the left. Jump across stars, rearrange them, \
     and cruise through an endless universe generated in real-time by AI.";

const CARD_2_ICON: &str = "🚀";
const CARD_2_TITLE: &str = "PLANETARY DESCENT";
const CARD_2_DESC: &str =
    "Double-click any star and watch your rocket blast straight to the surface. \
     A secondary AI model immediately spawns unique flora and fauna for that world.";

const CARD_3_ICON: &str = "🪐";
const CARD_3_TITLE: &str = "TRUE SURVIVAL";
const CARD_3_DESC: &str =
    "Explore uncharted planets and try to stay alive. No fake scripts: just pure, \
     physically accurate simulation running completely on your own GPU.";

#[component]
pub fn AboutPage() -> Element {
    rsx! {
        div {
            class: "min-h-screen w-full relative overflow-hidden bg-[#0f1116]",

            div {
                class: "absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[700px] \
                       bg-white/[0.02] blur-[130px] rounded-full pointer-events-none",
            }
            div {
                class: "absolute bottom-0 left-1/4 w-[600px] h-[400px] \
                       bg-white/[0.015] blur-[100px] rounded-full pointer-events-none",
            }

            Header {}

            div {
                class: "relative z-10 flex flex-col items-center justify-center \
                       min-h-[calc(100vh-120px)] px-8 py-16",

                h1 {
                    class: "font-serif-glow text-4xl md:text-5xl text-white \
                           drop-shadow-[0_0_15px_rgba(255,255,255,0.7)] \
                           drop-shadow-[0_0_35px_rgba(255,255,255,0.3)] \
                           select-none tracking-[0.2em]",
                    style: "font-family: {FONT_SERIF}",
                    "{PAGE_TITLE}"
                }

                div {
                    class: "w-64 flex items-center my-9",
                    div { class: "flex-1 h-[1px] bg-white/30" }
                    div {
                        class: "mx-3 w-1.5 h-1.5 rounded-full bg-white/50 \
                               drop-shadow-[0_0_8px_rgba(255,255,255,0.6)]",
                    }
                    div { class: "flex-1 h-[1px] bg-white/30" }
                }

                div {
                    class: "max-w-2xl mx-auto bg-white/[0.03] backdrop-blur-md \
                           border border-white/[0.06] rounded-2xl p-8 md:p-10 mb-14 \
                           text-center",

                    p {
                        class: "text-white/60 text-sm md:text-[15px] leading-relaxed tracking-wide",
                        style: "font-family: {FONT_SANS}",
                        "{MAIN_DESCRIPTION}"
                    }
                }

                div {
                    class: "grid grid-cols-1 md:grid-cols-3 gap-5 max-w-5xl w-full",

                    div {
                        class: "group bg-white/[0.02] backdrop-blur-md border border-white/[0.04] \
                               rounded-xl p-7 text-center \
                               hover:bg-white/[0.05] hover:border-white/10 \
                               hover:shadow-[0_0_30px_rgba(255,255,255,0.05)] \
                               transition-all duration-500 cursor-default",

                        div {
                            class: "text-2xl mb-4 text-white/70 group-hover:text-white/90 \
                                   group-hover:drop-shadow-[0_0_10px_rgba(255,255,255,0.4)] \
                                   transition-all duration-500",
                            style: "font-family: {FONT_SERIF}",
                            "{CARD_1_ICON}"
                        }
                        h3 {
                            class: "text-white/85 text-[11px] uppercase tracking-[0.3em] mb-3 \
                                   font-semibold",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_1_TITLE}"
                        }
                        p {
                            class: "text-white/40 text-[13px] leading-relaxed",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_1_DESC}"
                        }
                    }

                    div {
                        class: "group bg-white/[0.02] backdrop-blur-md border border-white/[0.04] \
                               rounded-xl p-7 text-center \
                               hover:bg-white/[0.05] hover:border-white/10 \
                               hover:shadow-[0_0_30px_rgba(255,255,255,0.05)] \
                               transition-all duration-500 cursor-default",

                        div {
                            class: "text-2xl mb-4 text-white/70 group-hover:text-white/90 \
                                   group-hover:drop-shadow-[0_0_10px_rgba(255,255,255,0.4)] \
                                   transition-all duration-500",
                            style: "font-family: {FONT_SERIF}",
                            "{CARD_2_ICON}"
                        }
                        h3 {
                            class: "text-white/85 text-[11px] uppercase tracking-[0.3em] mb-3 \
                                   font-semibold",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_2_TITLE}"
                        }
                        p {
                            class: "text-white/40 text-[13px] leading-relaxed",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_2_DESC}"
                        }
                    }

                    div {
                        class: "group bg-white/[0.02] backdrop-blur-md border border-white/[0.04] \
                               rounded-xl p-7 text-center \
                               hover:bg-white/[0.05] hover:border-white/10 \
                               hover:shadow-[0_0_30px_rgba(255,255,255,0.05)] \
                               transition-all duration-500 cursor-default",

                        div {
                            class: "text-2xl mb-4 text-white/70 group-hover:text-white/90 \
                                   group-hover:drop-shadow-[0_0_10px_rgba(255,255,255,0.4)] \
                                   transition-all duration-500",
                            style: "font-family: {FONT_SERIF}",
                            "{CARD_3_ICON}"
                        }
                        h3 {
                            class: "text-white/85 text-[11px] uppercase tracking-[0.3em] mb-3 \
                                   font-semibold",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_3_TITLE}"
                        }
                        p {
                            class: "text-white/40 text-[13px] leading-relaxed",
                            style: "font-family: {FONT_SANS}",
                            "{CARD_3_DESC}"
                        }
                    }
                }
            }
        }
    }
}