[package]
name = "lunar-frontend"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

[[bin]]
name = "lunar-frontend"
path = "src/main.rs"

[dependencies]
dioxus = { version = "0.7.1", features = ["router"] }
lunar-structures = { path = "../lunar-structures" }
lunar-stellar-core = { path = "../lunar-stellar-core" }
lunar-ui-shared = { path = "../lunar-ui-shared" }
image = "0.25.10"
base64 = "0.23.1"
serde_json = "1"
tracing = "0.1"

[target.'cfg(all(target_family= "wasm", not(target_os = "wasi")))'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "WebGl2RenderingContext",
    "HtmlCanvasElement",
    "Window",
    "Document",
    "Element",
    "DomRect",
    "Storage",
    "console",
    "Performance",
] }
gloo-timers = {version = "0.4.0", features = ["futures"]}

[target.'cfg(not(all(target_family = "wasm", not(target_os = "wasi"))))'.dependencies]
tokio = { version = "1", features = ["time"] }

[features]
default = ["desktop"]
web = ["dioxus/web", "dioxus/document", "lunar-ui-shared/web"]
desktop = ["dioxus/desktop", "lunar-ui-shared/desktop"]
mobile = ["dioxus/mobile"]